# Generated by Django 3.1.7 on 2021-03-01 13:51

from django.db import migrations, models
import photography_site.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('site_category', '0004_auto_20210301_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=photography_site.utilities.file_upload_name),
        ),
    ]
