# Generated by Django 3.1.7 on 2021-03-01 12:58

from django.db import migrations, models
import photography_site.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('site_photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to=photography_site.utilities.file_upload_name),
        ),
    ]
