# Generated by Django 3.1.7 on 2021-03-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_photo', '0002_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visit',
            field=models.IntegerField(null=True),
        ),
    ]
