# Generated by Django 3.1.7 on 2021-03-01 13:24

from django.db import migrations, models
import photography_site.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('site_photo', '0003_photo_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photography_site.utilities.file_upload_name),
        ),
        migrations.AlterField(
            model_name='photo',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
