# Generated by Django 3.1.7 on 2021-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_photo', '0004_auto_20210301_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
