# Generated by Django 3.1.7 on 2021-03-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_photo', '0007_auto_20210305_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='visit',
        ),
    ]
