# Generated by Django 3.1.7 on 2021-03-01 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='CopyRight',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site_setting',
            name='about_us_service',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site_setting',
            name='about_us_title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
